#!/usr/bin/env node
// Mutation check: proves the suite catches real bugs. Each mutant plants one
// bug in a temp copy of the script and runs the tests that should catch it.
// A mutant that SURVIVES (its tests still pass) means a coverage hole.
// Run: npm run test:mutation   (slow: a few minutes)
import { readFileSync, writeFileSync, mkdtempSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import path from 'node:path';

const original = readFileSync(new URL('../EVE_SLT_Tracker.user.js', import.meta.url), 'utf8');
const dir = mkdtempSync(path.join(tmpdir(), 'eve-mutant-'));

const MUTANTS = [
  { name: 'saved lists keep non-object entries', suite: 'stability',
    from: "    return !!entry && typeof entry === 'object' && !Array.isArray(entry);", to: '    return true;' },
  { name: 'a failing tick step is logged every tick', suite: 'stability',
    from: '        failingTickSteps.add(name);', to: '' },
  { name: 'a failing tick step escapes the loop', suite: 'stability',
    from: '    } catch (error) {\n      if (!failingTickSteps.has(name)) {', to: '    } catch (error) {\n      throw error;\n      if (!failingTickSteps.has(name)) {' },
  { name: 'TestView status cache unbounded', suite: 'stability',
    from: '    while (testViewStatusCache.size > MAX_TESTVIEW_STATUS_ENTRIES) {', to: '    while (testViewStatusCache.size > Infinity) {' },
  { name: 'removed card still copies its serial', suite: 'jiraux',
    from: '        serialBox.disabled = gone;', to: '        serialBox.disabled = false;' },
  { name: 'removed-from-rack card not marked', suite: 'jiraux',
    from: "      card.classList.toggle('eve-alert-gone', gone);", to: "      card.classList.toggle('eve-alert-gone', false);" },
  { name: 'retest counted as removed', suite: 'jiraux',
    from: '      const gone = !now || now.serial !== serial;', to: "      const gone = !now || now.serial !== serial || now.color !== 'red';" },
  { name: 'no TestView link while retesting', suite: 'jiraux',
    from: "        link: testViewRunUrl(serial)\n", to: "        link: false && testViewRunUrl(serial)\n" },
  { name: 'ticket prompt ignores a RUNNING test in TestView', suite: 'jiraux',
    from: '    if (running === true) {\n      // PuTTY would refuse it now', to: '    if (false) {\n      // PuTTY would refuse it now' },
  { name: 'TestView FAILED counted as running', suite: 'jiraux',
    from: '              done(status ? /running|in[ _-]?progress/i.test(status) : null);', to: '              done(status ? true : null);' },
  { name: 'gold outline on a chip whose test is running', suite: 'jiraux',
    from: "      if (pretest && !testRunning && !jiraAttentionSeen(serial, failedAt, 'attn')) {", to: "      if (pretest && !jiraAttentionSeen(serial, failedAt, 'attn')) {" },
  { name: 'green mark fades instantly on hover', suite: 'jiraux',
    from: '  const JIRA_NEW_FADE_MS = 3 * 1000;', to: '  const JIRA_NEW_FADE_MS = 0;' },
  { name: 'no PuTTY instruction on the pre-test no-ticket page', suite: 'jiraux',
    from: '    ], ticketHowTo(serial, failedAt, running));', to: '    ], null);' },
  { name: 'gold PuTTY box before the Jira bot had 15 min', suite: 'jiraux',
    from: '    if (Date.now() - failedAt < JIRA_CREATE_BY_HAND_MS) {\n      return {\n        plain: true,', to: '    if (false) {\n      return {\n        plain: true,' },
  { name: 'plain PuTTY line styled like the gold box', suite: 'jiraux',
    from: "        box.className = howto.plain ? 'eve-howto-plain' : 'eve-howto';", to: "        box.className = 'eve-howto';" },
  { name: 'gold acknowledgement not remembered (back after reload)', suite: 'jiraux',
    from: '      if (pretest && !testRunning && !jiraAttentionSeen(serial, failedAt, \'attn\')) {', to: '      if (pretest && !testRunning && !button.dataset.attnArmed) {' },
  { name: 'green mark not remembered across reloads', suite: 'jiraux',
    from: "    if (mark && mark.state === 'new' && mark.key === result.key) {", to: "    if (false) {" },
  { name: 'green acknowledgement not remembered (back after reload)', suite: 'jiraux',
    from: "          setJiraAttention(serial, failedAt, 'new', { state: 'seen' });\n", to: '' },
  { name: 'gold chip dims with an old card', suite: 'jiraux',
    from: '.eve-alert.eve-alert-aged .eve-jira-group:has(.eve-jira-attn) {\n  position: relative;\n  z-index: 2;', to: '.eve-alert.eve-alert-aged .eve-jira-group:has(.eve-jira-attn) {\n  position: relative;\n  z-index: auto;' },
  { name: 'pre-test "create one" only at 20 min', suite: 'jiraux',
    from: '  const JIRA_CREATE_BY_HAND_MS = 15 * 60 * 1000;', to: '  const JIRA_CREATE_BY_HAND_MS = 20 * 60 * 1000;' },
  { name: 'screen wake lock never taken', suite: 'keepawake',
    from: '      holdKeepAliveLock();\n      holdScreenWakeLock();', to: '      holdKeepAliveLock();' },
  { name: 'no catch-up refresh after a sleep', suite: 'keepawake',
    from: '    if (refresh) {\n      refreshNow();\n    }\n    holdScreenWakeLock();', to: '    holdScreenWakeLock();' },
  { name: 'Jira glow lost on repaint', suite: 'jiraux',
    from: "    button.classList.toggle('eve-jira-fresh', !!button.querySelector('.eve-jira-new'));", to: '' },
  { name: 'Jira copy copies the bare key, not the link', suite: 'jiraux',
    from: "      const link = found ? jiraIssueUrl(result.key) : '';", to: "      const link = found ? result.key : '';" },
  { name: 'Jira badge on a repaint / first look (no pending check)', suite: 'jiraux',
    from: '      if (button.dataset.wasPending === \'1\') {\n        // A real no-ticket', to: '      if (true) {\n        // A real no-ticket' },
  { name: 'Jira badge never fades after hover', suite: 'jiraux',
    from: '          setJiraAttention(serial, failedAt, \'new\', { state: \'seen\' });\n          clearJiraNewBadge(badge);', to: '          setJiraAttention(serial, failedAt, \'new\', { state: \'seen\' });' },
  { name: 'pre-test outline never fades after hover', suite: 'jiraux',
    from: "          button.classList.remove('eve-jira-attn');", to: '' },
  { name: 'pre-test outline missing', suite: 'jiraux',
    from: "        cls += ' eve-jira-attn';", to: '' },
  { name: 'hover fade is instant', suite: 'jiraux',
    from: '  const JIRA_HOVER_FADE_MS = 10 * 1000;', to: '  const JIRA_HOVER_FADE_MS = 0;' },
  { name: 'Jira copy control shown without a ticket', suite: 'jiraux',
    from: '      copy.hidden = !found;', to: '      copy.hidden = false;' },
  { name: 'pre-test no-ticket label reverted', suite: 'jiraux',
    from: '      text = pretest ? (testRunning ? \'No ticket (re-testing)\' : \'No ticket (create one)\') : \'No ticket\';', to: '      text = \'No ticket\';' },
  { name: 'shift guess ignores the early-arrival window', suite: 'logic',
    from: '    const opens = id => shiftMinutes(SHIFTS[id].start) - SHIFT_EARLY_MIN;', to: '    const opens = id => shiftMinutes(SHIFTS[id].start);' },
  { name: 'pre-test failure reported as test failure', suite: 'logic',
    from: "return oldColor === 'lightblue' ? 'PRETEST_FAILURE' : 'TEST_FAILURE';", to: "return 'TEST_FAILURE';" },
  { name: 'retest start (red -> lightgreen) alerts', suite: 'logic',
    from: "if (newColor === 'darkgreen' && oldColor === 'lightgreen') {", to: "if ((newColor === 'darkgreen' || newColor === 'lightgreen') && (oldColor === 'lightgreen' || oldColor === 'red')) {" },
  { name: 'CSV formula-injection guard removed', suite: 'logic',
    from: "if (/^[=+\\-@\\t\\r]/.test(text)) {", to: 'if (false) {' },
  { name: 'flap protection disabled', suite: 'rack',
    from: 'const ALERT_COOLDOWN_MS = 60000;', to: 'const ALERT_COOLDOWN_MS = 0;' },
  { name: '"Notifs off" section still surfaces alerts', suite: 'rack',
    from: '    if (!sectionSettings.watch) {\n      log(', to: '    if (false) {\n      log(' },
  { name: 'card click opens old Server Detail', suite: 'rack',
    from: '      openTestView(record.serial, openExternal);\n      return;', to: '      openExternal(record.detailUrl);\n      return;' },
  { name: 'server swap raises an alert', suite: 'rack',
    from: '    if (serialChanged) {\n      log(', to: '    if (false) {\n      log(' },
  { name: 'origin guard removed', suite: 'testview',
    from: '    if (!isTestViewOrigin()) {\n      return;\n    }\n    const serial', to: '    const serial' },
  { name: 'oldest TestView test chosen', suite: 'testview',
    from: '      matches.sort((a, b) => String(b.started || \'\').localeCompare(String(a.started || \'\')));\n      return matches.length ? String(matches[0].id) : \'\';', to: '      matches.sort((a, b) => String(a.started || \'\').localeCompare(String(b.started || \'\')));\n      return matches.length ? String(matches[0].id) : \'\';' },
  { name: 'view: window reintroduced', suite: 'static',
    from: 'const opts = { bubbles: true, cancelable: true, button: 0, buttons: 1 };',
    to: 'const opts = { bubbles: true, cancelable: true, view: window, button: 0, buttons: 1 };' },
  { name: 'native form submission not cancelled on Query press', suite: 'testview',
    from: '      if (form && event.target === form) {\n        event.preventDefault();', to: '      if (false) {\n        event.preventDefault();' },
  { name: 'cross-tab event claim ignored', suite: 'dedupe',
    from: '    if (findEventClaim(key, info.serial, transition, oldState.seen)) {',
    to: '    if (false && findEventClaim(key, info.serial, transition, oldState.seen)) {' },
  { name: 'claim matched by serial only (later event swallowed)', suite: 'dedupe',
    from: '    return claim && Number(claim.at) >= seenAt ? claim : null;',
    to: '    return claim || null;' },
  { name: 'second installed copy not idled', suite: 'dedupe',
    from: '    if (!claimThisTab()) {\n      return;\n    }', to: '    claimThisTab();' },
  { name: 'retry overlaps an in-flight confirmation', suite: 'dedupe',
    from: 'if (attempts >= RESULT_RETRY_MAX_ATTEMPTS || confirmationsInFlight.has(record.id)) {',
    to: 'if (attempts >= RESULT_RETRY_MAX_ATTEMPTS) {' },
  { name: 'new event reuses the cached detail result', suite: 'dedupe',
    from: '    return confirmPhase(info.detailUrl, info, { force: true })', to: '    return confirmPhase(info.detailUrl, info)' },
  { name: 'any page change advances the sighting time', suite: 'dedupe',
    from: '      if (relevant.some(touchesTable)) {', to: '      if (relevant.length) {' },
  { name: 'PASS card keeps the live Jira button', suite: 'jira',
    from: '    if (isPassResult(record)) {\n      clearTimeout(button.__eveJiraPoll);', to: '    if (false) {\n      clearTimeout(button.__eveJiraPoll);' },
  { name: 'PASS toast click goes to Jira', suite: 'jira',
    from: "&& !!serial && !isPassResult(record);", to: '&& !!serial;' },
  { name: 'title span stretches again (thin drag strip)', suite: 'ui',
    from: '#eve-alert-toggle { cursor: pointer; user-select: none; }', to: '#eve-alert-toggle { cursor: pointer; user-select: none; flex: 1; }' },
  { name: 'post-drag click not swallowed (drag from title folds)', suite: 'ui',
    from: '      setTimeout(() => {\n        draggedEnough = false;\n      }, 0);', to: '      draggedEnough = false;' },
  { name: 'drag measured from the header box (creep)', suite: 'ui',
    from: "      const rect = container.getBoundingClientRect();\n      dragState = {", to: "      const rect = header.getBoundingClientRect();\n      dragState = {" },
  { name: 'Jira key shown for a non-found result', suite: 'jira',
    from: "    } else if (result && result.state === 'waiting') {\n      cls += ' eve-jira-waiting';\n      text = pretest ? 'No ticket yet' : 'Ticket pending';",
    to: "    } else if (result && result.state === 'waiting') {\n      cls += ' eve-jira-waiting';\n      text = 'MFGS-0';" },
  { name: 'export times follow the PC clock, not Fremont', suite: 'timezone',
    from: "const SITE_TIME_ZONE = 'America/Los_Angeles';", to: 'const SITE_TIME_ZONE = undefined;' },
  { name: 'chronological record prints stored PC-clock time', suite: 'timezone',
    from: '`[${index + 1}] ${at.date || entry.date} ${at.time || entry.time} \\u{2014} `',
    to: '`[${index + 1}] ${entry.date} ${entry.time} \\u{2014} `' },
  { name: 'detail page Finished time ignored (detection time logged)', suite: 'timezone',
    from: '    if (happened) {\n      entry.eventIso = happened;', to: '    if (false) {\n      entry.eventIso = happened;' },
  { name: 'implausible Finished time accepted', suite: 'timezone',
    from: 'if (at > detected + EVENT_TIME_SKEW_MS || at < detected - EVENT_TIME_MAX_AGE_MS) {', to: 'if (false) {' },
  { name: 'actions menu ignores outside clicks', suite: 'ui',
    from: '        if (isOpen() && !menu.contains(event.target) && !button.contains(event.target)) {',
    to: '        if (false) {' },
  { name: 'actions menu never opens upward (off-screen near the bottom)', suite: 'ui',
    from: '        below + height > window.innerHeight - PANEL_MARGIN\n', to: '        false\n' },
  { name: 'closing the menu leaves Dismiss all armed', suite: 'ui',
    from: "      button.classList.remove('eve-menu-open');\n      onClose();", to: "      button.classList.remove('eve-menu-open');" },
  { name: 'actions menu clipped by the panel (absolute, not fixed)', suite: 'ui',
    from: '#eve-alert-menu {\n  position: fixed;', to: '#eve-alert-menu {\n  position: absolute;' },
  { name: 'log cleared at the selected shift\'s own window (Day wipes a running Graveyard)', suite: 'shiftlog',
    from: 'const removed = pruneLogBefore(logRetentionFloorAt(at));', to: 'const removed = pruneLogBefore(win.opens.getTime());' },
  { name: 'Log shift tooltip not updated when the shift changes', suite: 'shiftlog',
    from: '    if (select.title !== title) {', to: '    if (false) {' },
  { name: 'Auto flips shift mid-session (no sticky window)', suite: 'shiftlog',
    from: '      if (win.key === stored && now < win.closes.getTime()) {', to: '      if (false) {' },
  { name: 'manual shift pick never expires', suite: 'shiftlog',
    from: "    if (!settings || !SHIFTS[settings.logShiftChoice] || logShiftOverride(now)) {", to: '    if (true) {' },
  { name: 'old hand-picked shift not migrated to Auto', suite: 'shiftlog',
    from: '    delete loaded.logShift;\n', to: "    if (SHIFTS[loaded.logShift]) { loaded.logShiftChoice = loaded.logShift; loaded.logShiftOverrideFor = 'legacy'; }\n    delete loaded.logShift;\n" },
  { name: 'Jira chip shows the project key again', suite: 'jira',
    from: '      text = jiraChipText(result.key);', to: '      text = result.key;' },
  { name: 'red-cell click intercepts modifier clicks', suite: 'cellclick',
    from: '      event.button !== 0 ||\n      event.ctrlKey ||\n', to: '      event.button !== 0 ||\n' },
  { name: 'red-cell click intercepts any colour', suite: 'cellclick',
    from: "    if (!table || normalizeColor(cell) !== 'red') {", to: '    if (!table) {' },
  { name: 'red-cell click intercepts any table / column', suite: 'cellclick',
    from: '    if (!group || !group.headers.some(header => header.column === cell.cellIndex)) {', to: '    if (false) {' },
  { name: 'red-cell click lets the old detail link fire too', suite: 'cellclick',
    from: '    event.preventDefault();\n    event.stopPropagation();\n    devLog(`Red cell', to: '    devLog(`Red cell' },
  { name: 'Finished read as UTC, not Fremont time', suite: 'timezone',
    from: '    for (let i = 0; i < 2; i += 1) {\n      const p = isoDateParts', to: '    for (let i = 0; i < 0; i += 1) {\n      const p = isoDateParts' }
];

let survived = 0;
for (const m of MUTANTS) {
  if (!original.includes(m.from)) {
    console.log(`?? ${m.name}: anchor not found - update tests/mutation.mjs`);
    survived += 1;
    continue;
  }
  const file = path.join(dir, 'mutant.user.js');
  writeFileSync(file, original.replace(m.from, m.to));
  const r = spawnSync(process.execPath, ['--test', '--test-concurrency=1', `tests/${m.suite}.test.mjs`],
    { env: { ...process.env, EVE_SCRIPT: file }, encoding: 'utf8' });
  const killed = r.status !== 0;
  if (!killed) survived += 1;
  const failing = (r.stdout.match(/^not ok \d+ - .*/gm) || []).slice(0, 2).join(' | ');
  console.log(`${killed ? 'KILLED  ' : 'SURVIVED'} ${m.name}${killed ? `  <- ${failing}` : ''}`);
}
console.log(`\n${MUTANTS.length - survived}/${MUTANTS.length} mutants killed`);
process.exit(survived ? 1 : 0);
